import { Button } from "antd"
import type { GooglePhotosMediaItem, GooglePhotosPickerSession, GooglePhotosStatus } from "../lib/batchDomain"

type Props = {
  folderInputRef: React.RefObject<HTMLInputElement | null>; scanning: boolean; selectedFolderLabel: string | null; onScan: (files: FileList | null) => void
  googleStatus: GooglePhotosStatus | null; googleBusy: boolean; media: GooglePhotosMediaItem[]; selectedIds: string[]; nextPageToken: string | null; session: GooglePhotosPickerSession | null
  onPrimary: () => void; onConfig: () => void; onClearToken: () => void; onConnect: () => void; onImport: () => void; onToggleMedia: (id: string) => void; onLoadMore: () => void
  identifying: boolean; pendingCount: number; itemCount: number; progress: { done: number; total: number } | null; message: string | null; error: string | null; onIdentifyAll: () => void; onClearAll: () => void
}
export function BatchImportPanel(p: Props) {
  return <>
    <div className="section-heading"><div><h2>批量识别入库</h2><p className="muted">支持本地文件夹或 Google Photos 导入，逐条识别、微调后提交到云端（图片入 OSS）。</p></div></div>
    <div className="scan-row"><div className="field scan-input"><span>本地文件夹</span><Button htmlType="button" type="primary" onClick={() => p.folderInputRef.current?.click()} disabled={p.scanning}>{p.scanning ? "上传中…" : "选择文件夹并上传"}</Button><input ref={p.folderInputRef} type="file" multiple className="hidden-folder-input" onChange={(event) => p.onScan(event.target.files)} {...({ webkitdirectory: "", directory: "" } as Record<string, string>)} /><span className="field-help">{p.selectedFolderLabel ?? "点击按钮后直接选择本地文件夹，无需再手填路径。"}</span></div></div>
    <div className="field"><span>Google Photos</span><div className="upload-actions"><Button htmlType="button" type="primary" onClick={p.onPrimary} disabled={p.googleBusy || p.googleStatus?.enabled === false}>{p.googleBusy ? "处理中…" : p.googleStatus?.connected ? "重新连接 Google Photos" : p.googleStatus?.auth_configured === false ? "配置 Google Photos" : "连接 Google Photos"}</Button>{p.googleStatus?.enabled !== false ? <Button htmlType="button" type="text" onClick={p.onConfig} disabled={p.googleBusy}>修改配置</Button> : null}{p.googleStatus?.auth_configured ? <Button htmlType="button" type="text" danger onClick={p.onClearToken} disabled={p.googleBusy}>清除授权</Button> : null}{p.googleStatus?.connected ? <><Button htmlType="button" type="text" onClick={p.onConnect} disabled={p.googleBusy}>打开 Picker 选图</Button><Button htmlType="button" type="primary" onClick={p.onImport} disabled={p.googleBusy || p.selectedIds.length === 0}>{p.googleBusy ? "导入中…" : `导入所选图片（${p.selectedIds.length}）`}</Button></> : null}</div><span className="field-help">{p.googleStatus?.detail ?? "点击按钮后可在前端直接填写 Google Photos OAuth 配置，再通过 Google Picker 选图导入。"}</span>{p.googleStatus?.connected && p.media.length > 0 ? <><div className="tag-row">{p.media.map((item) => <Button key={item.id} htmlType="button" size="small" type={p.selectedIds.includes(item.id) ? "primary" : "default"} className="google-photo-chip" onClick={() => p.onToggleMedia(item.id)}>{p.selectedIds.includes(item.id) ? "已选" : "选择"} · {item.filename}</Button>)}</div><div className="existing-artifact-gallery">{p.media.map((item) => <button key={`google-photo-${item.id}`} type="button" data-ui="interactive-surface" className={`existing-artifact-thumb ${p.selectedIds.includes(item.id) ? "selected-action" : ""}`} onClick={() => p.onToggleMedia(item.id)} title={item.filename}><img src={item.thumbnail_url ?? item.base_url} alt={item.filename} loading="lazy" /></button>)}</div>{p.nextPageToken ? <div className="upload-actions"><Button htmlType="button" type="text" onClick={p.onLoadMore} disabled={p.googleBusy || !p.session?.id}>加载更多</Button></div> : null}</> : null}</div>
    <div className="upload-actions"><Button htmlType="button" type="primary" onClick={p.onIdentifyAll} disabled={p.identifying || p.googleBusy || p.pendingCount === 0}>{p.identifying ? "识别中…" : `开始识别（${p.pendingCount} 张待识别）`}</Button><Button htmlType="button" type="text" danger onClick={p.onClearAll} disabled={p.identifying || p.scanning || p.googleBusy || p.itemCount === 0}>全部清除</Button>{p.progress ? <span className="muted">进度 {p.progress.done}/{p.progress.total}</span> : null}</div>
    {p.message ? <p className="success-text">{p.message}</p> : null}{p.error ? <p className="error-text">{p.error}</p> : null}{p.itemCount === 0 ? <div className="empty-state"><strong>暂无待处理图片</strong><p className="muted">点击上方按钮选择本地文件夹，或连接 Google Photos 导入图片。</p></div> : null}
  </>
}
